name: tactool
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2020.6.20
  - libffi=3.4.2
  - openssl=1.1.1s
  - pip=22.2.2
  - python=3.11.0
  - setuptools=65.5.0
  - sqlite=3.40.1
  - tk=8.6.12
  - tzdata=2022g
  - vc
  - vs2015_runtime
  - wheel=0.37.1
  - wincertstore
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
    - altgraph==0.17.3
    - asttokens==2.2.1
    - attrs==22.2.0
    - backcall==0.2.0
    - colorama==0.4.6
    - decorator==5.1.1
    - executing==1.2.0
    - flake8==6.0.0
    - future==0.18.3
    - iniconfig==2.0.0
    - ipdb==0.13.11
    - ipython==8.8.0
    - jedi==0.18.2
    - matplotlib-inline==0.1.6
    - mccabe==0.7.0
    - numpy==1.24.1
    - packaging==23.0
    - pandas==1.5.3
    - parso==0.8.3
    - pefile==2022.5.30
    - pickleshare==0.7.5
    - pluggy==1.0.0
    - prompt-toolkit==3.0.36
    - pure-eval==0.2.2
    - pycodestyle==2.10.0
    - pyflakes==3.0.1
    - pygments==2.14.0
    - pyinstaller==5.7.0
    - pyinstaller-hooks-contrib==2022.15
    - pyqt5==5.15.7
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.11.0
    - pytest==7.2.1
    - pytest-qt==4.2.0
    - python-dateutil==2.8.2
    - pytz==2022.7.1
    - pywin32-ctypes==0.2.0
    - six==1.16.0
    - stack-data==0.6.2
    - traitlets==5.8.1
    - wcwidth==0.2.6
