name: Generate Environments

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/environments.yml"
      - "environments/unversioned-environment.yml"

jobs:
  create-environment-file:
    strategy:
      matrix:
        os: [windows, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Anaconda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: tactool-${{ matrix.os }}
          python-version: 3.11
          auto-activate-base: false
      - name: Install Packages
        shell: bash -l {0}
        # Update the existing environment with the given YAML file, prune removes packages not in YAML
        run: conda env update -f environments/unversioned-environment.yml --prune
      - name: Create Environment File
        shell: bash -l {0}
        run: |
          mkdir generated_environments
          conda env export > generated_environments/${{ matrix.os }}-environment.yml
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: environment-files
          path: generated_environments/${{ matrix.os }}-environment.yml
