name: Create distributable files

on:
  release:
    types:
      - released

jobs:
  # build-windows:
  #   runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Create Anaconda Environment
  #     uses: conda-incubator/setup-miniconda@v2
  #     with:
  #       environment-file: windows-environment.yml
  #       python-version: 3.11
  #       auto-activate-base: false

  #   - name: Build with PyInstaller
  #     shell: bash -l {0}
  #     run: pyinstaller --name=hello-world --windowed --paths=. --onefile app/main.py

  #   - name: Get Release Info
  #     id: get_release
  #     uses: bruceadams/get-release@v1.3.2
  #     env:
  #       GITHUB_TOKEN: ${{ github.token }}

  #   - name: Add Asset to Release
  #     uses: actions/upload-release-asset@v1
  #     env:
  #       GITHUB_TOKEN: ${{ github.token }}
  #     with:
  #       upload_url: ${{ steps.get_release.outputs.upload_url }}
  #       asset_path: dist/hello-world.exe
  #       asset_name: hello-world.exe
  #       asset_content_type: application

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Create Anaconda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: macos-environment.yml
          python-version: 3.11
          auto-activate-base: false
  
      - name: Build with PyInstaller
        shell: bash -l {0}
        run: |
          pyinstaller --name=hello-world --windowed --paths=. --onefile app/main.py
          ls -p dist/ | grep -v /
  
      - name: Get Release Info
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
  
      - name: Add Asset to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: dist/hello-world
          asset_name: hello-world.app
          asset_content_type: application
