name: Generate Requirements

on:
  push:
    branches:
      - main
    paths:
      - requirements/**
      - .github/workflows/requirements.yml

jobs:
  test:
    strategy:
      matrix:
        os: [windows, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install pip-tools
      run: pip install pip-tools

    - name: Compile requirements
      run: |
        pip-compile requirements/tiff-converter/${{ matrix.os }}_requirements.in --output-file requirements/tiff-converter/${{ matrix.os }}_requirements.txt
        pip-compile requirements/tiff-converter/${{ matrix.os }}_requirements_dev.in --output-file requirements/tiff-converter/${{ matrix.os }}_requirements_dev.txt

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: requirements-files
        path: |
          requirements/tiff-converter/${{ matrix.os }}_requirements.txt
          requirements/tiff-converter/${{ matrix.os }}_requirements_dev.txt
