name: Generate Requirements

on:
  push:
    branches:
      - main
    paths:
      - requirements/**
      - .github/workflows/requirements.yml

jobs:
  test:
    strategy:
      matrix:
        os: [windows, macos]
        project: [tiff-converter]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install pip-tools
      run: pip install pip-tools

    - name: Compile requirements
      run: |
        mkdir -p tmp/requirements/${{ matrix.os }}/
        cp requirements/${{ matrix.project }}/*.in tmp/requirements/
        pip-compile requirements/${{ matrix.project }}/requirements.in --output-file tmp/requirements/${{ matrix.os }}/requirements.txt
        pip-compile requirements/${{ matrix.project }}/requirements_dev.in --output-file tmp/requirements/${{ matrix.os }}/requirements_dev.txt

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: requirements
        path: tmp/requirements/
