name: Run TACtool

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/run-tactool.yml"

jobs:
  build:
    strategy:
      matrix:
        os: [windows, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v3

    - name: Activate Anaconda Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environments/${{ matrix.os }}-environment.yml
        python-version: 3.11
        auto-activate-base: false

    - name: Run TACtool
      shell: bash -l {0}
      run: |
        export PYTHONPATH=./tactool_files/
        python tactool_files/tactool/main.py --dev
