name: Create Distributable Files TACtool

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/tactool.yml"

jobs:
  build:
    strategy:
      matrix:
        os: [macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v3

    - name: Activate Anaconda Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environments/${{ matrix.os }}-environment.yml
        python-version: 3.11
        auto-activate-base: false

    - name: Build with PyInstaller
      shell: bash -l {0}
      run: |
        pyinstaller --name=tactool --windowed --paths=./tactool_files/ --onefile tactool_files/tactool/main.py
        cd dist
        zip -r tactool-macos.zip tactool.app
        cd ..

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: tactool-${{ matrix.os }}.zip
        path: tactool-macos.zip
