name: Test

on:
  push:
    branches:
      - main
    paths:
      - '**.py'

jobs:
  test:
    strategy:
      matrix:
        os: [windows, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v3
    - name: list files
      shell: bash -l {0}
      run: ls -a

    - name: Create Anaconda Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environments/${{ matrix.os }}-environment.yml
        python-version: 3.11
        auto-activate-base: false

    - name: Lint
      shell: bash -l {0}
      run: flake8

    - name: Test
      shell: bash -l {0}
      run: |
        export PYTHONPATH=.
        pytest -vs test/
